title: ""
description: "Fun apps available on the App Store"
baseurl: "/public-website"
url: "https://aaron-spencer.github.io"

repository: aaron-spencer/public-website

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jemoji

# Ensure pages are processed
include: ["_pages"]

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

author:
  name: "Aaron Spencer"
  # avatar: "{{ site.baseurl }}/assets/images/WhatsTheScoreIcon.jpg"
  bio: "Network, Cloud, Infrastructure Leader and Developer. App Developer on the side :slightly_smiling_face:"
  location: "NYC Area"
  email: your-email@example.com
  links:
    - label: "Linked-In"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/aspencer"

paginate: 5 # amount of posts to show
paginate_path: /page:num/

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOQN8kHg"
    category_name        : "Feedback"
    category_id          : "DIC_kwDOQN8kHs4Cxo0Y"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "preferred_color_scheme"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      classes: wide
      comments: true
  # home
  - scope:
      path: ""
      type: home
    values:
      layout: single
      author_profile: true
      classes: wide
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
      comments: true
