title: Aaron Spencer Apps
email: your-email@example.com
description: >-
  Fun apps available on the App Store
baseurl: "/public-website/"
url: ""
twitter_username: yourusername
github_username: yourusername

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

author:
  name: "Aaron Spencer"
  avatar: ""
  bio: "Network, Cloud, Infrastructure Leader and Developer. App Developer on the side :smile:"
  location: "NYC Area"
  links:
    - label: "Linked-In"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/aspencer"